src/assets/styles/index.css, src/components/Subscription.vue
- Refactor button into custom class
=> Refactor button

src/components/SiteFooter.vue, src/components/SiteNav.vue
- Fix alignment for site nav (with logo), footer, and main content
=> Fix alignment site nav, footer, and main content

src/components/Reopening.vue, src/views/Country.vue
- Change date format on home and country pages
=> Change date format

src/constants/travel.yaml
AE - updated domestic source
ZA - updated domestic source
DE - updated domestic status
=> Update to AE, ZA & DE

src/constants/travel.yaml
- DE: added domestic source
- AD: changed domestic and VQ source and status
- AF: added domestic and VQ source
- AG: changed domestic and VQ source and status
- AL: updated inbound, outbound and VQ Source
=> 25 June YAML Update (Gab)

src/constants/travel.yaml
=> Iceland Domestic Status Change.yaml

src/constants/travel.yaml
- updated Canada
- updated Iceland
- updated Armenia
- updated Angola
- updated Argentina
=> 26 June Changes Pt. 2

public/data/IS_international.md
- Updated information for Iceland Outbound Travel 
- Fixed broken link in Iceland Outbound Travel
=> cheryl-IS-update

public/data/IE_domestic.md
changes made as per @jannwong 's comments: `Face masks will be compulsory on public transport, restaurants, and shops. Barbershops, churches, theatres, cinemas, and gyms will also be allowed to reopen under certain hygiene conditions. People will also be allowed to resume domestic travel.`
=> Update IE domestic

src/constants/travel.yaml
- Updated DO
- Updated AR
- Updated ZM
- Updated BR
- Updated CR
- Updated ZA
- Updated ME
- Updated JO
- Updated MM
- Updated LY
- Updated IE
- Updated CL
- Updated SD
- Updated UG
=> Daily YAML Update Pt. 1

src/constants/travel.yaml
- Updated PL
- Updated IR
- Updated AT
- Updated MZ
- Updated TN
- Updated MG
- Updated DZ
- Updated AE
- Updated DO
- Updated BB
=> 30 June Updates

public/data/IN_international.md
Changed inbound international updates to point form for easier readability
=> IN international updates

src/components/CovidStats.vue, src/components/CovidStatsFigure.vue, src/views/Country.vue, vue.config.js
=> Covid cases

TW_domestic.md, TW_international.md, TW_visa_quarantine.md, wordlist.txt
=> Add TW files via upload

src/components/TravelStateLegend.vue, src/components/WorldMap.vue, src/router/index.ts
- On a smaller device: When a user selects a country, render the map in place
- Improve styling map title to decrease attention and make it fit better on smaller devices too
=> Fix rendering map

src/constants/travel.yaml
- Updated AZ
- Updated BA
- Updated HR
- Updated TW
- Updated BD
=> 1 July Update Pt. 2

src/components/CountrySelect.vue, src/constants/countries.js, src/store/index.ts, vue.config.js
* allows searching by country aliases using keys found in [dataset](https://datahub.io/core/country-codes):
* country name appearing in dropdown
* ISO3166-1-Alpha-3
* UNTERM English Formal
* removes accent marks (diacritics) in searches and URLs
=> Search country using aliases

src/constants/travel.yaml
- Updated BG
- Updated CA
- Updated CU
- Updated BS
- Updated JP
- Updated NG
- Updated CN
=> 2 July Changes

vue.config.js
https://ssr.vuejs.org/guide/hydration.html
https://markus.oberlehner.net/blog/how-to-pre-render-vue-powered-websites-with-webpack/#further-optimizations
=> Add flag to disable client-side hydration

src/constants/travel.yaml
- Updated CZ
- Updated MA
- Updated EG
- Changed update date for RU (no change for Russia restrictions)
- Updated GA
- Updated IN
- Updated PH
- Updated LB
- Updated CD
=> 3 July Changes

src/components/CountryBody.vue, src/views/Country.vue
- Change the text for when we don't have enough data
- Refactor the block so that it always shows
=> Change copy

src/assets/styles/index.css, src/components/TravelState.vue, src/components/TravelStateBadge.vue, src/components/TravelStateLegend.vue, src/components/WorldMap.vue, src/views/About.vue
- Create `TravelStateBadge` Component
- Create a new legend for the About page
- Refactor `TravelState` component to use `TravelStateBadge`
- Refactor `TravelStateLegend` component to use `TravelStateBadge`
- Refactor `WorldMap`
=> Travel state badge

src/constants/travel.yaml
- Updated MM
- Updated BD
- Updated XV
- Updated KZ
- Updated JO
- Updated KW
- Updated PT
- Updated BR
- Updated IQ
- Updates RS
- Updated GR
- Updated MK
- Update MV
- Updated IE
- Updated CY
- Updated AU
- Updated RW
- Updated SC
- Updated ES
- Updated PK
- Updated IR
=> 6 July Updates

src/views/Country.vue
Was wrong about https://github.com/tourhero/travel-reopening/pull/73#issuecomment-654588424 looks like the proerer way to do it is to encode the space
=> Encode mail space

src/components/CovidStatsFigure.vue
=> Place y-axis ticks on the right

src/constants/travel.yaml
- Updated GY
- Updated XK
- Updated KE
- Updated IQ
- Updated MG
- Updated WS
- Updated MH
- Updated ES
- Updated GR
- Update BE
- Updated BH
- Updated BI
- Updated BJ
- Updated BN
- Updated BO
- Updated BT
- Updated BW
- Updated SK
- Updated BZ
=> 7 July Updates

src/views/Country.vue
- Move Visa & Quarantine panel below International Travel
=> Move visa & quarantine panel up

src/constants/travel.yaml
- Updated UA
- Updated DE
- Updated PH
- Updated EE
- Updated IT
- Updated AL
- Updated TD
- Update NZ
- Updated CH
- Updated CG
- Updated CF
- Updated CI
- Updated CH
=> 8 July Updates

src/constants/travel.yaml
- Updated Chile
- Updated NG
- Updated SD
- Updated LY
- Updated IL
- Updated DZ
- Updated IN
- Updated RS
- Updated AE
- Updated CO
- Updated CV
- Updated DK
- Updated DM
- Updated DJ
- Updated EC
- Updated ER
=> 9 July Updates

src/constants/travel.yaml
- Updated IT
- Updated SE
- Updated NO
- Updated HK
- Updated HR
- Updated MA
- Updated AE
- Updated CA
- Updated ID
- Updated CD
- Updated RS
- Updated SL
- Updated SD
- Updated KW
- Updated GM
=> 13 July Updates

src/constants/countries.js
Rollback previous country URL and display overridden names
=> Use CLDR column for URL

src/views/Country.vue
- Move country title and last updated on panel up
- Change wording to `last checked on`
=> Country header

src/components/CovidStats.vue
- Remove stringency index stats
- Change wording from `New confirmed cases` to `Daily new confirmed cases` (Approved by @jannwong )
=> Statistics panel

src/components/CountryTravelIdeas.vue
=> Fix email subject

src/constants/travel.yaml, src/store/index.ts, src/views/Country.vue
- Remove `last-updated` YAML key and values
- Remove references in methods and templates
- Add `checkedOn` to template set to today's date for now
=> Clean up last updated yaml key

src/components/CovidStatsFigure.vue
- Change `2020` tick on the `x-axis` to `January`
=> Change 2020 tick to January

src/components/WorldMap.vue
Changed to the plural form of entry and exit travel resriction's' as there are multiple countries displayed
=> Changed to the plural form

src/views/Country.vue
Add `id` for country subscribe link
=> Add id for country subscribe link

src/constants/travel.ts, src/constants/travel.yaml, src/views/Country.vue
- Add `checked_on` key to YAML
- Create a function to get the value of the `checked_on` key that is used in the template
=> Last checked on date

src/components/CovidStatsDate.vue, src/components/CovidStatsFigure.vue, src/views/Country.vue
- Add a link to https://www.ecdc.europa.eu/en/covid-19-pandemic
- Remove dates from `CovidStatsFigure`
- Add latest publication date for statistics
=> Data sources

README.md, src/components/Disclaimer.vue, src/components/Heading.vue, src/views/About.vue, src/views/Country.vue
- Create `Heading` component to be able to pass `h` tags from `Country` and `About` pages
- Use the `Disclaimer` component on both pages
- Change copy regarding `About Our Data`
- Minor text improvements
- Adapt text READ.ME accordingly
=> Disclaimer

src/components/ShareNetwork.vue, src/main.ts
=> Change icons

src/constants/travel.yaml
- Updated MD countries
- Updated countries that are part of ‘Travel Reopening’
- Updated PH
- Updated DJ
- Updated US
- Updated CA
- Updated RW
- Updated PA
- Updated BR
- Updated DZ
- Updated HU
- Updated KE
- Updated GN
=> 21 July Update and Changes

src/assets/styles/index.css, src/components/CountryTravelIdeas.vue, src/components/CovidStats.vue, src/components/SiteFooter.vue, src/components/SubscriptionForm.vue, src/components/TitleMapSelect.vue, src/constants/travel.yaml, src/views/About.vue, src/views/Country.vue
- Improve legibility of text
- Fix and improve spacing of elements
- Add header for when a user subscribes for updates
=> Styling fixes

src/constants/travel.yaml
- Updated IQ
- Updated ZA
- Updated ES
- Updated AU
- Updated CZ
- Updated EG
- Updated PA
- Updated US
- Updated DO
- Updated DJ
- Updated NE
- Updated HK
- Updated BS
- Updated HN
- Updated VE
- Updated FR
- Updated JP
- Updated ID
- Updated AR
- Updated LY
- Updated FR
=> 22 July Updates

src/components/WorldMap.vue
=> Change map title

package.json, src/customTypings/vue-schema-microdata.d.ts, src/main.ts, src/views/Country.vue, yarn.lock
Adds microdata based on https://schema.org/Article
=> Add microdata

src/constants/travel.yaml
- LR
- QA
- AT
- JO
- CD
- PA
- UG
- PG
- ZW
- NP
- GR
- CR
=> 23 July Changes

src/components/ShareNetwork.vue
- Change URLs, description, and quote
=> Change URLS, description, and quote

src/constants/countries.js
- Add `UAE` alias for the United Arab Emirates in county select dropdown
=> Add UAE search alias for United Arab Emirates

src/constants/travel.yaml
- MA
- DZ
- PT
- IQ
- JO
- KH
- KP
=> 28 July Update

src/constants/travel.yaml
- RW
- CG
- PG
- VN
- BE
- LB
- BG
- HN
- KE
- HK
- GH
- MG
- UZ
- JM
- TN
- ZA
=> 29 July Update

tailwind.config.js
- Purge unused CSS classes
**`app.css` before CSS purge**
**`app.css` after CSS purge**
=> Purge unused CSS classes

src/constants/travel.yaml
- TH
- NG
- KZ
- DE
- CO
- BD
- BS
- US
- GR
- OM
- KW
=> 30 July Updates

vue.config.js
=> Change name PWA

src/components/ShareNetwork.vue, src/components/TitleMapSelect.vue
- Change copy intro text and add icon
- Improve spacing header elements
- Improve spacing sharing icons
- Change URLs for sharing icons
=> Implement header changes

src/constants/travel.yaml
- JM
- CA
- LY
- PH
- RO
- CR
- BR
- KW
- IQ
- SB
- BE
- SK
- AU
- LB
- NZ
- VN
- MN
- SE
- WS
- IT
- SO
- AR
- FJ
- NA
- ST
- CI
- TG
- CN
- SB
- BG
- BW
- MM
- ZA
- CU
=> 3 August Updates (for 31 July, 1 Aug and 2 Aug

src/components/CountryTravelIdeas.vue, src/components/CovidStats/Panel.vue, src/components/Disclaimer.vue, src/components/SiteFooter.vue, src/components/SiteNav.vue, src/components/TitleMapSelect.vue, src/views/About.vue
- Open links in new tabs
- Add `rel` attributes with `nofollow` values
=> Open links in new tabs

src/components/SiteNav.vue
Turn subscribe link into a button in the navigation bar
=> Turn subscribe link into a button

src/components/Map/WorldMap.vue
Style single tooltip
❌ Needs to be rebased after https://github.com/tourhero/travel-reopening/pull/203
=> Style tooltip

src/components/Reopening.vue
- Change content for the reopening section
- Style the reopening section
=> Change content and style reopening section

src/constants/travel.yaml
- KP
- KN
- PH
- JP
- PL
- TD
- CY
- DO
- AZ
- HN
- VE
=> 5 August Updates + Blog Post Links

src/constants/travel.yaml
- GM
- IE
- PY
- MA
- TZ
- HK
- BE
- HN
- TR
- MV
- JO
- IQ
- BB
=> 6 August Updates (Distill + MD + Discrepancies)

README.md
Update project setup instructions
=> Update project setup instructions

src/constants/travel.yaml
- PK
- GW
- JP
- MZ
- GM
- DO
- DE
- US
- OM
- FR
- MO
=> 7 August Updates

src/components/ContentNav.vue, src/components/SiteNav.vue, src/router/index.ts, src/views/Country.vue, tailwind.config.js
- Create `ContentNav` component
- Add `ContentNav` component to `Country` page
- Add anchor links
- Change `SiteNav` border to match with `ContentNav`
=> Content navigation

src/views/About.vue
- Change the text for the legend section on the About page
- Style accordingly
=> Change text for Legend section and style

src/constants/travel.yaml
- AM
- MT
- TL
- OM
- LY
- MA
- KR
- US
- CH
- NO
- AT
- MW
- DZ
- DE
- PG
- PK
- IQ
- KY
- CU
- CA
- IT
- KN
=> 11 August Update

src/components/ContentNav.vue
- Add IDs for content nav links
- Reindent
=> Add ids to content nav links

src/App.vue, src/components/SubscriptionForm.vue, src/views/About.vue, src/views/Country.vue, src/views/NotFound.vue, src/views/Subscribe.vue
- Change the header tag of the `Subscribe` page from `h2` to `h1`
- Change the title for the `Subscribe` page
- Override parent meta content descriptions (fix duplicate meta content descriptions)
- Shorten the meta `title` for the `App`
- Edit the meta info for the `About` page
- Edit the meta info for the `Country` pages
- Edit the title for the `NotFound` page
- Add meta info for the `NotFound` page
=> Semrush fixes

src/components/Map/WorldMap.vue
Revert disable click on map for mobile
Reverting https://github.com/tourhero/travel-reopening/pull/166/
=> Revert disable click on mobile map

public/index.html, src/App.vue, src/router/index.ts, src/views/OembedMap.vue
- Allow for nested routes
- Move 404 route to bottom (wildcard route should be last)
- Show selected country
=> Fix nested routes
